### PR TITLE
New low level - with tree as list of possibly lists.

### PR DESCRIPTION
**Pull request by dneise**
This low level API should implement chapter 2 of "eventio_en.pdf". Not more.
The only pulic function is the topmost function in `eventio/event_io_file.py` called `object_tree`, since it returns the tree containing the eventio objects. 

The representation for this tree is a list of tuples like this:

```
tree = [
    (H0, D0), 
    (H1, [
        (H1_0, D1_0), 
        (H1_1, D1_1),
    ]), 
    (H2, [
        (H2_0, [
            (H2_0_0, D2_0_0)
        ]),
    ]),
]
```

where `H???` is an instance of `ObjectHeader` and `D???` is an instance of `ObjectData`. 
As one can see, the tuples can either be: `(H, D)` or `(H, [...])`, where the `list` can contain any number of these tuples again.

### CODE REVIEW

**Comment by dneise** [comment]
I have referenced this PR to the branch named `new_low_level`, in order to make the comparison easier. I think ultimately this should be compared to the master though.

**Comment by MaxNoe** [comment]
This looks good.

One thing I miss in comparison to the current master:
There is no differentiating between known and unknown objects. For the exploration of a file, it was really helpfull to see that. The object tree only shows ObjectHeaders with typenumbers. I think the __repr__ with `UnknownObject(type=xxxx)` for unknown objects and `CorsikaRunHeader` for something we know should be there.

**Comment by dneise** [comment]
Okay now the tests pass again.

I would like to see now, if we can decide for or against this proposal for a different low-level API of this project, i.e. everything currently in `event_io_file.py`.

The driving points behind this alternative proposal are:

### Less to Read

In my understanding 'event_io_file.py` contains everything needed to unpack the binary file into its constituent "EventIOObjects" arranged in a tree like fashion. It is with ~150 lines pretty short and can thus quickly be read by new developers. 

### Less to Learn 

It introduces only two new classes `ObjectHeader` and `ObjectData` with a flat class hierarchy. No inheritance is used. The only free function `object_tree(filelike)` returns a list of tuples. Here comes the first complication: These tuples are either `(header, data)` or `(header, [...])`.
`header` is always simple `namedtuple`. If the 2nd tuple item is not a list, it is an `ObjectData` instance. `ObjectData` is harder to grasp since it is just a wrapper around its only useful member `value`. Its only purpose being to delay fetching of the payload. 
It is a pity, but I found no way around that.... 

### Decoupling Direct File Access

File pointer modification (by `read` and `seek`) is entirely confined to `event_io_file.py`. Restricting direct file access improves decoupling and thus increases testability. Also is should make stuff easier to understand.

**Comment by dneise** [comment]
> There is no differentiating between known and unknown objects. For the exploration of a file, it was really helpfull to see that. The object tree only shows ObjectHeaders with typenumbers. I think the repr with UnknownObject(type=xxxx) for unknown objects and CorsikaRunHeader for something we know should be there.

For the low level api in `event_io_file.py` everything is unknown. So this remark goes on level higher. 
I don't disagree. But I believe everything higher than this low level API, still calls for a complete rewrite. 

It is after all just one example of how the low level stuff might be used....

**Comment by dneise** [comment]
I changed the base back to the `master` so a review and possibly a merge is possible.

**Comment by MaxNoe** [comment]
Ok, if we say this is our new (even lower level) abstraction of EventIO i would agree and I like it!

But I would only merge it back into master when the features we currently have there are reimplemented on top of this low level stuff.

I won't be able to code much in the next two weeks, but after that I will look into it.

**Comment by dneise** [comment]
One remark: I think the name `event_io_file.py` is badly chosen by me. Do you have a good idea? 
Also: Should this low-level api be in the root-level of the package? Or pushed further down? I guess the low level stuff should be pushed deeper down and the upcoming high level stuff should be pulled up, right? 

> But I would only merge it back into master when the features we currently have there are reimplemented on top of this low level stuff.

In order not to break the master? Makes sense. On the other hand ... the tests are passing. So I guess tests are missing... (big surprise :-)

How to proceed? Would it make sense to "freeze" this branch and branch off of it to repair the higher level stuff?

**Comment by MaxNoe** [comment]
I do not want to play captain obvious, but to make the tests pass, you changed them ;)

Before there were tests like `isinstance(obj, CorsikaRunHeader)` to see if the object was recognised correctly.

**Comment by dneise** [comment]
> I do not want to play captain obvious, but to make the tests pass, you changed them ;)

This is not playing captain obvious ... it is a valid question. 
So a test defines an API and the code passes only if it implements this API. 

By changing a test, I changed the API, which I think should be used. 
I think for example we should not test for types but for behaviour, so I dropped most `isinstace` tests.

**Comment by dneise** [comment]
But this is again a higher level discussion.

**Pull request closed without merging**
