### PR TITLE
New api

### PR DESCRIPTION
**Pull request by MaxNoe**
Basically a rewrite of the inner structure.

* There is now a class `EventIOFile` which gives low level access to `EventIOObjects`
* There is a class `IACTFile` which reads in `EventIO` files as written by the CORSIKA IACT Extension and gives random access to the events therein.

## Low level access

If an Object has only subitems, making it known to `eventio` is just:
```{python}
class MyNewObject(EventIOObject):
    ''' My really fancy new EventIO Object '''
    eventio_type = 666

eventio.objects.known_types[MyNewObject.eventio_type] = MyNewEventIOType
``` 

If an item contains data itself, this should be returned as nicely formatted python objects (e.g. numpy structured arrays or a namedtuple or ...) by the `parse_data_field` method.

This is how our test file with one shower now loos like:
```
In [1]: import eventio
In [2]: eventio.EventIOFile('eventio/resources/one_shower.dat')
Out[2]: 
EventIOFile(path=eventio/resources/one_shower.dat, objects=[
  CorsikaRunHeader(first=0, length=1096)
  CorsikaInputCard(first=1112, length=448)
  CorsikaTelescopeDefinition(first=1576, length=20)
  CorsikaEventHeader(first=1612, length=1096)
  CorsikaArrayOffsets(first=2724, length=16)
  CorsikaTelescopeData(first=2756, length=6136, subitems=1)
  CorsikaEventEndBlock(first=8908, length=1096)
  CorsikaRunEndBlock(first=10020, length=16)
])
```

## IACTFile

This iterates over events (including reused showers) in a given IACT eventio file.
Currently only the photon bunch data is read (and e.g. not the PhotoElectrons which can also be written by the bernlohr extension).

### CODE REVIEW

**Comment by dneise** [comment]
This PR is imho too big to be reviewed. Have a look at the diff, there is none ... there are a lot  deleted files and a lot of new files. Yes, there are some diffs as well .. but hardly any. This is basically a new project I assume.

I have no idea how to proceed in such a case. Has anybody an idea how to deal with such a case?

I see two ways:
 a) Check the branch out and execute the tests (which is exactly what Travis CI does) and thus gain confidence in the code and decide to merge it.
 b) Ask to take apart the huge PR into its constituents, so one has a chance to understand each part on its own. 

I tend to b) since a) would mean we can always merge, when the tests pass. No need for any peer review.

**Comment by dneise** [comment]
```{python}
In [9]: f = eventio.EventIOFile("eventio/resources/3_gammas_reuse_5.dat")

In [10]: f
Out[10]: 
EventIOFile(path=eventio/resources/3_gammas_reuse_5.dat, objects=[
  CorsikaRunHeader(first=0, length=1096)
  CorsikaInputCard(first=1112, length=436)
  CorsikaTelescopeDefinition(first=1564, length=20)
  CorsikaEventHeader(first=1600, length=1096)
	...
  CorsikaTelescopeData(first=333360, length=24776, subitems=1)
  CorsikaTelescopeData(first=358152, length=16712, subitems=1)
  CorsikaEventEndBlock(first=374880, length=1096)
  CorsikaRunEndBlock(first=375992, length=16)
])
```

this `__repr__` implies an EventIOFile to have members called `path` and `objects`, but it has only `path`. Isn't this a bit surprising? I think, there is nothing wrong with exposing `_objects` by naming it `objects`.

Actually why is `EventIOFile` a class and not really a python list of `EventIOObject`s? It seems the eventio file format being a container format is represented most easily as a python list, or nested list of lists, if we look at sub-objects.

**Comment by MaxNoe** [comment]
I fully agree with you, that the `__repr__` misleading, I'll fix that.

As for the simple list vs. class point. I think i just found it nice to have somthing called `<>File` for a file.

**Comment by MaxNoe** [comment]
`EventIOFile.objects` is "public" now.

**Comment by MaxNoe** [comment]
The `EventIOFile` keeps references to the opened file, so that reading of the payloads of the subitems is possible without them caring about file objects and compressions. They just use the read functions of the mother object, which i found kind of neat.

**Comment by MaxNoe** [comment]
I think we can merge this now and continue discussion about improvements in your `low_level` branch, OK?

**Comment by dneise** [comment]
yes lets merge. having many open PRs overloads my brain

**Pull request merged**
